exports.PERMISSIONS = [
  { key: 'VIEW_ADMIN', category: 'Administration', description: 'Accéder à l’interface administrative', defaultRoles: ['ADMIN','DEVELOPER','MODERATOR'] },
  { key: 'MANAGE_ROLES', category: 'Administration', description: 'Créer / modifier / supprimer des rôles', defaultRoles: ['ADMIN','DEVELOPER'] },
  { key: 'MANAGE_ANNOUNCEMENTS', category: 'Administration', description: 'Gérer les annonces / messages globaux', defaultRoles: ['ADMIN','DEVELOPER','MODERATOR'] },
  { key: 'VIEW_SYSTEM_LOGS', category: 'Administration', description: 'Consulter les journaux système', defaultRoles: ['ADMIN','DEVELOPER'] },
  { key: 'MANAGE_USERS', category: 'Modération', description: 'Modifier des utilisateurs', defaultRoles: ['ADMIN','MODERATOR','DEVELOPER'] },
  { key: 'BAN_USER', category: 'Modération', description: 'Bannir un utilisateur', defaultRoles: ['ADMIN','MODERATOR'] },
  { key: 'UNBAN_USER', category: 'Modération', description: 'Révoquer un bannissement', defaultRoles: ['ADMIN','MODERATOR'] },
  { key: 'MANAGE_BANNED_SLUGS', category: 'Modération', description: 'Gérer les slugs interdits', defaultRoles: ['ADMIN','MODERATOR','DEVELOPER'] },
  { key: 'EXTENDED_PLINKK_LIMIT', category: 'Utilisateur', description: 'Plinkk supplémentaires', defaultRoles: ['PARTNER','DEVELOPER','ADMIN'] },
  { key: 'EXTENDED_THEME_LIMIT', category: 'Utilisateur', description: 'Créer davantage de thèmes', defaultRoles: ['DEVELOPER','ADMIN'] },
  { key: 'CREATE_THEME', category: 'Contenu', description: 'Créer un thème', defaultRoles: ['USER','BETA','PARTNER','ADMIN','DEVELOPER'] },
  { key: 'APPROVE_THEME', category: 'Contenu', description: 'Approuver / rejeter des thèmes', defaultRoles: ['ADMIN','DEVELOPER','MODERATOR'] },
  { key: 'ARCHIVE_THEME', category: 'Contenu', description: 'Archiver des thèmes', defaultRoles: ['ADMIN','DEVELOPER'] },
  { key: 'RESET_2FA_USER', category: 'Sécurité', description: 'Réinitialiser 2FA utilisateur', defaultRoles: ['ADMIN','DEVELOPER'] },
  { key: 'VIEW_STATS', category: 'Statistiques', description: 'Voir les statistiques globales', defaultRoles: ['ADMIN','DEVELOPER','MODERATOR'] },
  { key: 'MANAGE_BANNED_EMAILS', category: 'Administration', description: 'Gérer les emails bannis', defaultRoles: ['ADMIN','MODERATOR','DEVELOPER'] },
  { key: 'MANAGE_SITE_SETTINGS', category: 'Administration', description: 'Paramètres généraux du site', defaultRoles: ['ADMIN','DEVELOPER'] },
  { key: 'MANAGE_COSMETICS_CATALOG', category: 'Administration', description: 'Gérer le catalogue de cosmétiques', defaultRoles: ['ADMIN','DEVELOPER'] },
  { key: 'MANAGE_PLINKK_SETTINGS_GLOBAL', category: 'Administration', description: 'Paramètres plinkk globaux', defaultRoles: ['ADMIN','DEVELOPER'] },

  { key: 'DELETE_PLINKK', category: 'Modération', description: 'Supprimer une Plinkk', defaultRoles: ['ADMIN','MODERATOR'] },
  { key: 'EDIT_ANY_PLINKK', category: 'Modération', description: 'Modifier n’importe quelle Plinkk', defaultRoles: ['ADMIN','MODERATOR','DEVELOPER'] },
  { key: 'VIEW_USER_PRIVATE_EMAIL', category: 'Modération', description: 'Voir les emails privés', defaultRoles: ['ADMIN','MODERATOR'] },
  { key: 'VIEW_PRIVATE_PAGES', category: 'Modération', description: 'Voir les pages privées', defaultRoles: ['ADMIN','MODERATOR','DEVELOPER'] },
  { key: 'SUSPEND_PLINKK', category: 'Modération', description: 'Suspendre une Plinkk', defaultRoles: ['ADMIN','MODERATOR'] },
  { key: 'MANAGE_REPORTS', category: 'Modération', description: 'Gérer les signalements', defaultRoles: ['ADMIN','MODERATOR'] },

  { key: 'CREATE_PLINKK', category: 'Contenu', description: 'Créer une Plinkk', defaultRoles: ['USER','BETA','PARTNER','ADMIN','DEVELOPER'] },
  { key: 'EDIT_PLINKK', category: 'Contenu', description: 'Modifier ses Plinkks', defaultRoles: ['USER','BETA','PARTNER','ADMIN','DEVELOPER'] },
  { key: 'DELETE_OWN_PLINKK', category: 'Contenu', description: 'Supprimer ses propres Plinkks', defaultRoles: ['USER','BETA','PARTNER','ADMIN','DEVELOPER'] },
  { key: 'PUBLISH_PLINKK', category: 'Contenu', description: 'Publier une Plinkk', defaultRoles: ['USER','BETA','PARTNER','ADMIN','DEVELOPER'] },
  { key: 'EDIT_ANY_THEME', category: 'Contenu', description: 'Modifier n’importe quel thème', defaultRoles: ['ADMIN','DEVELOPER'] },
  { key: 'DELETE_ANY_THEME', category: 'Contenu', description: 'Supprimer un thème', defaultRoles: ['ADMIN','DEVELOPER'] },
  { key: 'FEATURE_THEME', category: 'Contenu', description: 'Mettre un thème en avant', defaultRoles: ['ADMIN','DEVELOPER','MODERATOR'] },

  { key: 'CHANGE_USERNAME', category: 'Utilisateur', description: 'Changer le nom d’utilisateur (au-delà des limites)', defaultRoles: ['ADMIN','DEVELOPER'] },
  { key: 'CHANGE_EMAIL', category: 'Utilisateur', description: 'Changer l’email', defaultRoles: ['ADMIN','DEVELOPER'] },
  { key: 'EXPORT_DATA', category: 'Utilisateur', description: 'Exporter les données', defaultRoles: ['ADMIN','DEVELOPER'] },

  { key: 'VIEW_AUDIT_LOGS', category: 'Sécurité', description: 'Voir le journal d’audit', defaultRoles: ['ADMIN','DEVELOPER'] },
  { key: 'MANAGE_SECURITY_SETTINGS', category: 'Sécurité', description: 'Gérer les paramètres de sécurité', defaultRoles: ['ADMIN','DEVELOPER'] },

  { key: 'VIEW_LOGIN_STATS', category: 'Statistiques', description: 'Voir les stats de connexion', defaultRoles: ['ADMIN','DEVELOPER','MODERATOR'] },
  { key: 'VIEW_THEME_STATS', category: 'Statistiques', description: 'Voir les stats des thèmes', defaultRoles: ['ADMIN','DEVELOPER','MODERATOR'] },

  { key: 'RUN_MIGRATIONS', category: 'Développement', description: 'Lancer des migrations', defaultRoles: ['ADMIN','DEVELOPER'] },
  { key: 'SEED_DATABASE', category: 'Développement', description: 'Exécuter des seeds', defaultRoles: ['ADMIN','DEVELOPER'] },
  { key: 'ACCESS_DEV_TOOLS', category: 'Développement', description: 'Accéder aux outils développeur', defaultRoles: ['ADMIN','DEVELOPER'] },
  { key: 'MANAGE_API_KEYS', category: 'Développement', description: 'Gérer les clés API', defaultRoles: ['ADMIN','DEVELOPER'] },
  { key: 'MANAGE_WEBHOOKS', category: 'Développement', description: 'Gérer les webhooks', defaultRoles: ['ADMIN','DEVELOPER'] },
  { key: 'MANAGE_INTEGRATIONS', category: 'Intégrations', description: 'Configurer des intégrations', defaultRoles: ['ADMIN','DEVELOPER'] },
  { key: 'MANAGE_UMAMI', category: 'Intégrations', description: 'Configurer Umami / Analytics', defaultRoles: ['ADMIN','DEVELOPER'] },
  { key: 'MANAGE_ANALYTICS', category: 'Intégrations', description: 'Configurer les analytiques', defaultRoles: ['ADMIN','DEVELOPER'] },

  { key: 'VIEW_BILLING', category: 'Facturation', description: 'Voir la facturation', defaultRoles: ['ADMIN'] },
  { key: 'MANAGE_SUBSCRIPTIONS', category: 'Facturation', description: 'Gérer les abonnements', defaultRoles: ['ADMIN'] },
  { key: 'ISSUE_REFUNDS', category: 'Facturation', description: 'Émettre des remboursements', defaultRoles: ['ADMIN'] },
];
