exports.PERMISSIONS = [
  { key: 'VIEW_ADMIN', category: 'Administration', description: 'Accéder à l’interface administrative', defaultRoles: ['ADMIN','DEVELOPER','MODERATOR'] },
  { key: 'MANAGE_ROLES', category: 'Administration', description: 'Créer / modifier / supprimer des rôles', defaultRoles: ['ADMIN','DEVELOPER'] },
  { key: 'MANAGE_ANNOUNCEMENTS', category: 'Administration', description: 'Gérer les annonces / messages globaux', defaultRoles: ['ADMIN','DEVELOPER','MODERATOR'] },
  { key: 'VIEW_SYSTEM_LOGS', category: 'Administration', description: 'Consulter les journaux système', defaultRoles: ['ADMIN','DEVELOPER'] },
  { key: 'MANAGE_USERS', category: 'Modération', description: 'Modifier des utilisateurs', defaultRoles: ['ADMIN','MODERATOR','DEVELOPER'] },
  { key: 'BAN_USER', category: 'Modération', description: 'Bannir un utilisateur', defaultRoles: ['ADMIN','MODERATOR'] },
  { key: 'UNBAN_USER', category: 'Modération', description: 'Révoquer un bannissement', defaultRoles: ['ADMIN','MODERATOR'] },
  { key: 'MANAGE_BANNED_SLUGS', category: 'Modération', description: 'Gérer les slugs interdits', defaultRoles: ['ADMIN','MODERATOR','DEVELOPER'] },
  { key: 'EXTENDED_PLINKK_LIMIT', category: 'Utilisateur', description: 'Plinkk supplémentaires', defaultRoles: ['PARTNER','DEVELOPER','ADMIN'] },
  { key: 'EXTENDED_THEME_LIMIT', category: 'Utilisateur', description: 'Créer davantage de thèmes', defaultRoles: ['DEVELOPER','ADMIN'] },
  { key: 'CREATE_THEME', category: 'Contenu', description: 'Créer un thème', defaultRoles: ['USER','BETA','PARTNER','ADMIN','DEVELOPER'] },
  { key: 'APPROVE_THEME', category: 'Contenu', description: 'Approuver / rejeter des thèmes', defaultRoles: ['ADMIN','DEVELOPER','MODERATOR'] },
  { key: 'ARCHIVE_THEME', category: 'Contenu', description: 'Archiver des thèmes', defaultRoles: ['ADMIN','DEVELOPER'] },
  { key: 'RESET_2FA_USER', category: 'Sécurité', description: 'Réinitialiser 2FA utilisateur', defaultRoles: ['ADMIN','DEVELOPER'] },
  { key: 'VIEW_STATS', category: 'Statistiques', description: 'Voir les statistiques globales', defaultRoles: ['ADMIN','DEVELOPER','MODERATOR'] },
];
